# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

before_install:
  - gem install cocoapods

install:
  - brew update && brew upgrade swiftlint
  - cd Example
  - pod install
  - pod trunk register $ccpKey $ccpValue
  
language: swift
osx_image: xcode12.5
xcode_workspace: TSWebImageView.xcworkspace
xcode_scheme: TSWebImageView-Example
xcode_destination: platform=iOS Simulator,OS=14.6,name=iPhone 8

script: 
 - cd ..
 - swiftlint
 - cd Example
 - xcodebuild test -workspace 'TSWebImageView.xcworkspace' -scheme 'TSWebImageView-Example' -destination 'platform=iOS Simulator,OS=13.6,name=iPhone 8'
 - cd ..
 - pod spec lint
 - pod lib lint --allow-warnings --skip-tests
 - pod trunk push TSWebImageView.podspec
