# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile

xcode_workspace: Example/TSWebImageView.xcworkspace
xcode_scheme: TSWebImageView-Example
xcode_destination: platform=iOS Simulator,OS=12.1,name=iPhone X

before_install:
- cd Example
- pod install

# script:
# - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/TSWebImageView.xcworkspace -scheme TSWebImageView-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
# - pod lib lint
