# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: CocoaPods@0
  displayName: 'pod install'
  inputs:
    projectDirectory: '$(system.defaultWorkingDirectory)/Example'
    forceRepoUpdate: true

- task: Xcode@5 
  displayName: 'Build framework'
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: '**/*.xcodeproj/_Pods.xcodeproj'
    packageApp: false

- task: PublishBuildArtifacts@1
  displayName: "Publish Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop-framework'
    publishLocation: 'Container'